### ISSUE TITLE
can we make the circle with stripe or alternative color ,as below ? 

### ISSUE THREAD

**Issue by koolkarni** [bartgryszko/react-native-circular-progress#133]
![screen shot 2018-06-18 at 5 54 45 pm](https://user-images.githubusercontent.com/16875126/41628522-c773973c-73d9-11e8-8cc4-2dbca8af99ff.png)

**Comment by yeomann** [comment]
nice one but would be interesting to see the implementation. maybe I would try if I get some free time

**Comment by Jacse** [comment]
This seems to be a mixture of two requested features: #163 and #41. Let's keep discussion there.
