### ISSUE TITLE
View config not found for name RNSVGPath

### ISSUE THREAD

**Issue by suark** [bartgryszko/react-native-circular-progress#144]
I've tried looking for some issue related in the `react-native-svg` and I couldn't find it. But here is what I'm seeing.
![simulator screen shot - iphone 6 - 2018-07-05 at 15 44 16](https://user-images.githubusercontent.com/6233440/42402207-95aff3de-8136-11e8-8233-a6393031241e.png)

This is happening when passing values as 

```
<AnimatedCircularProgress
  size={74}  
  width={4}  
  prefill={50}  
  fill={50}  
  rotation={180}  
  tintColor='#00e0ff'  
  backgroundColor='white'   
/>
```

I don't believe I'm passing anything incorrectly.

We are using `"react-native": "0.55.4"`

I believe this issue only started happening after some recent changes, mainly updating from an older version of react-native.

**Comment by Jacse** [comment]
Have you installed and linked `react-native-svg`?

**Comment by suark** [comment]
@Jacse I'll recheck that there isn't a flaw in the `react-native-svg install`.

**Comment by suark** [comment]
<img width="794" alt="screen shot 2018-07-09 at 9 13 51 am" src="https://user-images.githubusercontent.com/6233440/42459166-7b930102-8358-11e8-9855-bea2a34d90b2.png">

Just checking and it appears like their is no issue with have `react-native-svg` installed and linked.

Do you think it's possible that breaking changes have happened in their library?

**Comment by truongluong1314520** [comment]
I got an error in version react-native 0.55.4 too but in Android. It because of the build.gradle use "implementation" instead of "compile".

I think iOS get error because of the way it link. I suggest you should link by manual instead of using react-native link command

**Comment by roysG** [comment]
Same for me, Version react: 0.54.4 
Any updates?

**Comment by freddessert** [comment]
From the `README` of `react-native-svg` library:
Android
npm install react-native-svg --save

Append the following lines to android/settings.gradle:

include ':react-native-svg'
project(':react-native-svg').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-svg/android')
Insert the following lines inside the dependencies block in android/app/build.gradle:

compile project(':react-native-svg')
Open up `android/app/src/main/java/[...]/MainApplication.java

Add import com.horcrux.svg.SvgPackage; to the imports at the top of the file
Add new SvgPackage() to the list returned by the getPackages() method. Add a comma to the previous item if there's already something there.

**Comment by Jacse** [comment]
Closing since this issue seems resolved
