### ISSUE TITLE
AnimatedCircularProgress as timer

### ISSUE THREAD

**Issue by jmaricic** [bartgryszko/react-native-circular-progress#155]
Is it possible to show AnimatedCircularProgress as a timer? I'd like to start the timer and show it's value inside AnimatedCircularProgress... Is that possible at all?

**Comment by Jacse** [comment]
Sure! You can just define the fill-value as a percentage of time elapsed

**Comment by Jacse** [comment]
I'm going to close this since it is not actionable.
