### ISSUE TITLE
Invariant Violation: requireNative Component: "RNSVGPath" was not found in the UIManager

### ISSUE THREAD

**Issue by mattmattkim** [bartgryszko/react-native-circular-progress#156]
HI, 

I've run on my project:
`npm i --save react-native-circular-progress react-native-svg
react-native link react-native-svg`

And immediately received this error while testing out this code:

`      <AnimatedCircularProgress
        size={120}
        width={15}
        fill={100}
        tintColor="#00e0ff"
        onAnimationComplete={() => console.log('onAnimationComplete')}
        backgroundColor="#3d5875"
      />
`

My setup:
`react-native-cli: 2.0.1
react-native: 0.56.0`

In my package.json
` "react-native-circular-progress": "^1.0.1"   
"react-native-svg": "^6.5.2",`

<img width="375" alt="screen shot 2018-09-11 at 11 44 47 am" src="https://user-images.githubusercontent.com/14237270/45352245-576a6300-b5b8-11e8-82dd-8952592d14e5.png">

**Comment by Jacse** [comment]
Installing the libraries and linking them are two seperate commands. So first you would install it with `npm i --save react-native-circular-progress react-native-svg` and then afterwards you would run `react-native link react-native-svg`

**Comment by mattmattkim** [comment]
Thanks for your quick reply!

I did do that,  i just don't know how to format line breaks in Github comments. :)

I discovered it was the react-native-svg library acting up. 
I fixed it using Cocoapods as described in #2 on this page:

https://www.npmjs.com/package/react-native-svg

**Comment by Tino-F** [comment]
I'm getting the same issue on a Samsung Galaxy S8 and this didn't work for me

**Comment by buddhishan** [comment]
For iOS, run `pod install` to install missing pods.

**Comment by ajkhatibi** [comment]
@amed was that with pods installed or without?

**Comment by PierreCapo** [comment]
I've solved this issue by doing the manual installation without pods:
https://github.com/react-native-community/react-native-svg#ios

**Comment by Jacse** [comment]
I’m going to close this issue since it’s about installing react-native-svg and not this component

**Comment by alittletf** [comment]
for any future person coming here with this issue that I faced on Android, make sure to recompile your project so RN picks up the native lib changes. I forgot this simple step

**Comment by NeliHarbuzava** [comment]
If auto-linking is not for your project, you should probably do following:
Add this to **ios/Podfile**:
```
pod 'RNSVG', path: '../node_modules/react-native-svg/RNSVG.podspec'
```

And then run `npx pod-install ios`.

This worked for me.

**Comment by tenslider** [comment]
@NeliHarbuzava thank you, your solution worked for me.

**Comment by Sprukstish** [comment]
If everything is linked correctly, just sync your project with Gradle files and rebuild your project in Android Studio.

**Comment by prateekchitransh1907** [comment]
> If auto-linking is not for your project, you should probably do following:
> Add this to **ios/Podfile**:
> 
> ```
> pod 'RNSVG', path: '../node_modules/react-native-svg/RNSVG.podspec'
> ```
> 
> And then run `npx pod-install ios`.
> 
> This worked for me.

Thank you.

**Comment by sokvebolkol** [comment]
@prateekchitransh1907, thank you. It works for me:)

**Comment by panktibardolia119933** [comment]
**Working Solution**

I uninstalled the application from my android device.
Then, run again 
npx react-native run-android **OR** react-native run-android (According to your setup)

**Comment by mariohandsome** [comment]
I'm try anything, but not work.
But, after that, I removed app in Simulator and Emulator, then run `yarn ios` and `yarn android`  to rebuild app again.
It work!!!

**Comment by GenaroNadile** [comment]
I checked the Podfile.lock inside `ios` folder and the path and from for RNSVG was `../node_modules/react-native-svg`, I changed it to `../node_modules/react-native-svg/apple` and it fixed the problem.
I don't know if that's a good practice but nothing seemed to work for me, only this.

**Comment by MarquesRick** [comment]
> Installing the libraries and linking them are two seperate commands. So first you would install it with `npm i --save react-native-circular-progress react-native-svg` and then afterwards you would run `react-native link react-native-svg`

works for me! tks

**Comment by jvlavan** [comment]
Try 
npm install react-native-svg
npm install react-native-svg-transformer
