### ISSUE TITLE
Update react-native-svg version in peerDependencies

### ISSUE THREAD

**Issue by pro-nasa** [bartgryszko/react-native-circular-progress#158]
RN 0.57 requires a react-native-svg 7.x

**Comment by pro-nasa** [comment]
"react-native-circular-progress@1.0.1" has incorrect peer dependency "react-native-svg@^6.3.1".

**Comment by markusl** [comment]
Could you possibly open a pull request to fix this? Thanks :)

**Comment by markusl** [comment]
react-native-svg updated to 8.0.10
