### ISSUE TITLE
How do I use this with Expo?

### ISSUE THREAD

**Issue by bloodelves88** [bartgryszko/react-native-circular-progress#160]
I'm trying to use this with Expo, and when attempting to build the app, I get this error: 

`
Unable to resolve "react-native-svg" from "node_modules/react-native-circular-progress/src/CircularProgress.js"
`

If I install `react-native-svg`, I get this error:

`
Tried to register two views with the same name RNSVGPath
`

I understand that Expo comes with its own `react-native-svg` already, which is why the error occurs. But `react-native-circular-progress` doesn't use [Expo's SVG](https://docs.expo.io/versions/v30.0.0/sdk/svg)... so how am I supposed to get around this issue?

Modifying CircularProgress.js to use Expo's SVG fixes this issue and works perfectly. But I'd prefer to use this without any modifications.

Any ideas?

**Comment by bloodelves88** [comment]
I decided to use version 0.2.0 of this package. Works for me and there's no issue with Expo

**Comment by stehrenberg** [comment]
Same issue. Is downgrading to 0.2.0 really the only way?

**Comment by markusl** [comment]
@stehrenberg did you try to run the included example app?

**Comment by phpsmarter** [comment]
if you use expo ,need modify some code

because of expo redefine SVG code  ,  need change some code in the sourcecode 

```
<Svg
          width={size}
          height={size}
          style={{ backgroundColor: 'transparent' }}
        >
          <Svg.G rotation={rotation} originX={size/2} originY={size/2}>
            { backgroundColor && (
              <Svg.Path
                d={backgroundPath}
                stroke={backgroundColor}
                strokeWidth={backgroundWidth || width}
                strokeLinecap={lineCap}
                fill="transparent"
              />
            )}
            {fill > 0 && (
              <Svg.Path
                d={circlePath}
                stroke={tintColor}
                strokeWidth={width}
                strokeLinecap={lineCap}
                fill="transparent"
              />
            )}
          </Svg.G>
        </Svg>
```

**Comment by RikusWiehahn** [comment]
How I fixed this:
1. Make sure react-native-svg is not in package.json
2. Delete package-lock.json
3. Delete node_modules
4. Run npm install

I think it's caused by react-native-svg being installed twice and the dependencies getting mixed up

**Comment by MehmetKaplan** [comment]
Is there any perminant solution for this issue? The abobe ones seems as workarounds.
