### ISSUE TITLE
can it be changed to liquid fill animation ?

### ISSUE THREAD

**Issue by souhaiebtar** [bartgryszko/react-native-circular-progress#168]

**Comment by Jacse** [comment]
Can you expand what you mean by liquid fill animation?

**Comment by souhaiebtar** [comment]
first thanks for responding, what i meant i something like this
![liquidFillAnimation](https://i.imgur.com/a2kgpK5.gif)

**Comment by Jacse** [comment]
That looks more like a linear progress bar instead of a circular one. I'm afraid this component is focused on circular progress indicators and does not support a progress bar like the animation you attached.

**Comment by souhaiebtar** [comment]
yes, it's a linear progress bar, thanks anyway
