### ISSUE TITLE
Nothing shows on my Screen - help wanted

### ISSUE THREAD

**Issue by lutakyn** [bartgryszko/react-native-circular-progress#169]
I am trying the library with this simple code and the error I get is **Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined**

```
 import React,{Component} from 'react';
import {Text, View, StyleSheet} from 'react-native';
import { AnimatedCircularProgress } from 'react-native-circular-progress';

export default class LayoutExample extends Component {
  constructor(props) {
  super(props)
  this.state = { fill: 0 }
}
  render() {
    return (
      <AnimatedCircularProgress
  size={200}
  width={3}
  fill={this.state.fill}
  tintColor="#00e0ff"
  backgroundColor="#3d5875">
  {
    (fill) => (
      <Text style={{width:100,height:100}}>
        { this.state.fill }
      </Text>
    )
  }
</AnimatedCircularProgress>
    );
  }
}
```

**Comment by markusl** [comment]
Hi. Did you try out the example app included in the repository? I just recently tested it and created it from scratch to avoid any problems.

BR,
Markus

**Comment by MrAlekhin** [comment]
The same for me. I've recently updated to react-native@0.57

**Comment by markusl** [comment]
@MrAlekhin same question for you. Did you try the included example app and if yes, was there any issues with that?

**Comment by lutakyn** [comment]
It worked eventually,i didn't use the fill well,however the rotation of 90 degrees doesn't work as expected,shouldn't the rotation be 0?
