### ISSUE TITLE
How to use reAnimated function?

### ISSUE THREAD

**Issue by Surangaup** [bartgryszko/react-native-circular-progress#171]
How to use **reAnimated** function here. any sample code?

**Comment by abrillo2** [comment]
//below code reanimates infinitely , and the circle is fullCircle  


<AnimatedCircularProgress
                    
                    ref={(ref) => this.circularProgress = ref}
                    size={300}
                    width={150}
                    fill={0}
                    duration={8000}
                    prefill={100}
                    tintColor="#73989d"
                    backgroundColor={PrimaryBgColour} 
                    onAnimationComplete={()=>{
                     this.circularProgress.reAnimate(100, 0,8000, Easing.ease)
                    }}
                    />

**Comment by Jacse** [comment]
Documentation has just been updated with more info on `reAnimated`. I'll close this for now.

**Comment by Jonnakutivijaykumar** [comment]
<AnimatedCircularProgress
                          size={50}
                          width={3}
                          fill={fill}
                          tintColor="#2874A6"
                          backgroundColor="#7FB3D5"
                          // duration={item.timer * 1000}
                          duration={30*1000}
                          prefill = {10}
                          rotation={-360}
                          // easing={Easing.bezier(.64, .62, .7, .69)}
                          easing={Easing.out(Easing.ease)}
                          lineCap="square"
                          // onAnimationComplete={() => this.onAnimationComplete(item,index)}
                          onAnimationComplete={()=>{
                            this.circularProgress.reAnimate(100, 0,8000, Easing.ease)
                           }}
                       >

**Comment by Jonnakutivijaykumar** [comment]
<AnimatedCircularProgress
                          size={50}
                          width={3}
                          fill={fill}
                          tintColor="#2874A6"
                          backgroundColor="#7FB3D5"
                          // duration={item.timer * 1000}
                          duration={30*1000}
                          prefill = {10}
                          rotation={-360}
                          // easing={Easing.bezier(.64, .62, .7, .69)}
                          easing={Easing.out(Easing.ease)}
                          lineCap="square"
                          // onAnimationComplete={() => this.onAnimationComplete(item,index)}
                          onAnimationComplete={()=>{
                            this.circularProgress.reAnimate(100, 0,8000, Easing.ease)
                           }}
                        >


in above  error says  reAnimate is undefined

**Comment by z00m1n** [comment]
The code above fails with `_this.circularProgress.reAnimate is not a function.` after the first animation has run. Is the code complete ? Or do I need to define `this.circularProgress` somewhere ?
