### ISSUE TITLE
peerDependency versions too high

### ISSUE THREAD

**Issue by lgraubner** [bartgryszko/react-native-circular-progress#178]
Is there a reason why the peerDependency version of React is `16.7.0`? The official supported Version from React Native is `16.6.3`.
Also it might make sense to change React Native version from `^0.57.8` to `>=0.57.8` (and maybe lower it).

I'm willing to make a PR, just want to make sure if there is any reasoning behind the current versions.

**Comment by Jacse** [comment]
No, there isn't. I don't know why this was updated; it creates versioning conflicts with Expo.

**Comment by Jacse** [comment]
Fixed in 85fb0c246a5aadffd20cb9d9f81b8d6019553fec
