### ISSUE TITLE
tintColor  or circlePath problem on IOS

### ISSUE THREAD

**Issue by Neck1T** [bartgryszko/react-native-circular-progress#179]
Hi. Problems with fill the circle on IOS (android works ok).

As I found problem in
`const circlePath = this.circlePath(size / 2, size / 2, size / 2 - width / 2, 0, arcSweepAngle * this.clampFill(fill) / 100);`
If I remove  **this.clampFill(fill) / 100** , it fills ok ( but full circle ).
![image](https://user-images.githubusercontent.com/31615366/54139330-fa961b00-4429-11e9-91ca-4f9a02f27d5b.png)

no expo 
"react": "^16.8.2",
"react-native": "^0.58.6",
"react-native-svg": "^9.3.3",
"react-native-circular-progress": "^1.1.0",

**Comment by Jacse** [comment]
What exactly is happening and what did you expect would happen? Does it not animate?

**Comment by Neck1T** [comment]
> What exactly is happening and what did you expect would happen? Does it not animate?

@Jacse As You can see - I indicated fill={60}.  But it did not fill it on IOS. On android it works ok

expected on IOS: fill={60}  with #77C744 
got on IOS: empty circle ( it did not fill it )

**Comment by AkilLis** [comment]
Same here tested on React native 0.59.0

**Comment by qvick1pro** [comment]
Downgrade react-native-svg to 8.0.10 resolving that issue

**Comment by Jacse** [comment]
Moving this to #181
