### ISSUE TITLE
Use as eta timmer

### ISSUE THREAD

**Issue by fadyshawky** [bartgryszko/react-native-circular-progress#184]
Hi, 
i need help to use this component as eta timer as it starts with the specified eta and ends when it arrives to zero.

Also i need the fill = 100 with the initial eta

thanks.

**Comment by markusl** [comment]
This is not really a bug in the library and I'm not sure what you are actually trying to achieve. Please feel free to reopen if there is an improvement request or a bug with the component.

BR,
Markus
