### ISSUE TITLE
Android - circle cropped on bottom and right side

### ISSUE THREAD

**Issue by adybuciuman** [bartgryszko/react-native-circular-progress#194]
Great library. On iOS is working great. but on Android the circle is cropped on right and bottom side. Any help would be appreciated

![image](https://user-images.githubusercontent.com/12176091/58472978-2a62de00-8150-11e9-9b09-3a44c0eb29b9.png)

**Comment by martinpiria** [comment]
Same happens to me

**Comment by ErwanDL** [comment]
I have also noticed this issue on both iOS and Android. It seems that changing the size of the circle to certain values can fix this (for example, odd percentages of total screen width on my Android phone), but these values are not the same for every device, so it makes it really hard to fix.

**Comment by markusl** [comment]
Could you post some example code that reproduces the issue? I just recently updated the example app and it would be helpful if you could test with that as well.

BR,
Markus

**Comment by PavelPolyakov** [comment]
This happened to me, when size of the chart was a floating number. For integers there is no such issue.

**Comment by Bang9** [comment]
@PavelPolyakov Thanks!

**Comment by markusl** [comment]
Looks like this one is solved.
