### ISSUE TITLE
Thanks @Jacse . I added your answer. Then I got this error.

### ISSUE THREAD

**Issue by Nfcsolutions** [bartgryszko/react-native-circular-progress#196]
Thanks @Jacse . I added your answer. Then I got this error.

`undefined is not a function (evaluating ' _this.circularProgressRef.animate(100, 8000, _reactNative.Easing.quad)')`

Thank you.

_Originally posted by @janaka120 in https://github.com/bartgryszko/react-native-circular-progress/issues/148#issuecomment-407362966_

**Comment by markusl** [comment]
Is this still a problem with the latest version?
