### ISSUE TITLE
Mind cutting master to npm?

### ISSUE THREAD

**Issue by dbarner1** [bartgryszko/react-native-circular-progress#197]
Would help resolve peer dependency peer dep missing error for everyone on RN 57.9 and above:

`npm ERR! peer dep missing: react-native@^0.57.8, required by react-native-circular-progress@1.1.0`

**Comment by markusl** [comment]
Could you be a little bit more specific what you mean by this?

**Comment by dbarner1** [comment]
This is no longer needed, since v1.3.0 was shipped to npm.

Thanks for checking in, and the work on this project @markusl!
