### ISSUE TITLE
Using react-native-circular-progress with Vue Native

### ISSUE THREAD

**Issue by akhtariali** [bartgryszko/react-native-circular-progress#205]
I'm trying to use react-native-circular-progress with Vue Native. Almost everything is cool, but when I try to fill the progress bar (write something inside it), I get this error:

![image](https://user-images.githubusercontent.com/46029474/64358764-4c57e080-d01c-11e9-8787-587404f261ba.png)

**This is my code:**
TEMPLATE:
```
    <AnimatedCircularProgress
      :size="120"
      :width="15"
      :fill="50"
      tintColor="#2B96D9"
      backgroundColor="#9CD941"
    >{{ () => fillCircularProgressBar() }}</AnimatedCircularProgress>

```
SCRIPT:
```
import { AnimatedCircularProgress } from "react-native-circular-progress";

export default {
  components: { AnimatedCircularProgress },
  data() {
    return {
      fill: "hello"
    };
  },
  methods: {
    fillCircularProgressBar: function() {
      return this.fill;
    }
  }
};
```

**Comment by akhtariali** [comment]
Hello! So I found a solution.
I created a JSX component:
```
export default animatedCircularProgressJSXFiller = (drinked, toDrink) => (
  <Text style={textAlignCenter}>
    <Text style={drinkedStyle}>{drinked}</Text>
    {"\n"}
    <Text style={toDrinkStyle}> of {toDrink} ml</Text>
  </Text>
);
```
Fed my Vue component with it:
```
  methods: {
    // Gets the JSXFiller and makes it available for other elements in the component
    animatedCircularProgressJSXGetter: animatedCircularProgressJSXFiller
  }
```
And finally used the method (function) as a prop in the component:
```
    <AnimatedCircularProgress
      :size="250"
      :width="15"
      :fill="progressBarFillPercentCalculator"
      :children="()=>animatedCircularProgressJSXGetter(50, 150)"
    ></AnimatedCircularProgress>
```

**Comment by yitelee** [comment]
Thanks for the idea of binding on ':children', I found following also works:

    <animated-circular-progress
		ref="acp1"
		:size="200"
		:width="3"
		:fill="fill"
		:onAnimationComplete="() => console.log('onAnimationComplete')"
		:children="(fill)=>getFill(fill)"
		backgroundColor="red"
		tintColor="blue"
    >
    </animated-circular-progress>
    <nb-button success :onPress="handleBtnPress"><nb-text>Success</nb-text></nb-button>

    .....................
    import { Easing } from "react-native";
    import { AnimatedCircularProgress } from 'react-native-circular-progress';
    import {View, Text} from 'react-native';

    ....................
    data: function() {
      return {
        fill: 0
      }
    },
    components: {
      AnimatedCircularProgress
    },
    methods: {
      handleBtnPress: function() {
        this.$refs.acp1.animate(100, 8000, Easing.quad);
      },
      getFill: function(fill) {
        return (<Text>{fill}</Text>);
      }
    }

**Comment by akhtariali** [comment]
> Thanks for the idea of binding on ':children', I found following also works:
> 
> ```
> <animated-circular-progress
> 	ref="acp1"
> 	:size="200"
> 	:width="3"
> 	:fill="fill"
> 	:onAnimationComplete="() => console.log('onAnimationComplete')"
> 	:children="(fill)=>getFill(fill)"
> 	backgroundColor="red"
> 	tintColor="blue"
> >
> </animated-circular-progress>
> <nb-button success :onPress="handleBtnPress"><nb-text>Success</nb-text></nb-button>
> 
> .....................
> import { Easing } from "react-native";
> import { AnimatedCircularProgress } from 'react-native-circular-progress';
> import {View, Text} from 'react-native';
> 
> ....................
> data: function() {
>   return {
>     fill: 0
>   }
> },
> components: {
>   AnimatedCircularProgress
> },
> methods: {
>   handleBtnPress: function() {
>     this.$refs.acp1.animate(100, 8000, Easing.quad);
>   },
>   getFill: function(fill) {
>     return (<Text>{fill}</Text>);
>   }
> }
> ```

Yes. This is also a good solution. I, personally, prefer to keep JSX out of Vue components. This also may be helpful:
https://vue-native.io/docs/render-prop.html
