### ISSUE TITLE
dashedBackground bug?

### ISSUE THREAD

**Issue by aboveyunhai** [bartgryszko/react-native-circular-progress#219]
I have tried out the `dashedBackground` attribute and it's not parsed into `strokeDashedarray` correctly;
the problem code in `CircularProgress.js` line 88-90

    const dashedBackgroundStyle = dashedBackground.gap > 0
      ? `${dashedBackground.width}, ${dashedBackground.gap}`
      : dashedBackground;

when I passed the dashedBackground to the Component
` dashedBackground={{width:10, gap:20}}`

![image](https://user-images.githubusercontent.com/35160613/69596282-16e5e200-0fd0-11ea-8cb3-ef36857c57a2.png)

So I had modified the code to correct structure
```
    const dashedBackgroundStyle = dashedBackground.gap > 0
      ? dashedBackground
      : { width:0, gap:0 };
```

and the expect output.
![image](https://user-images.githubusercontent.com/35160613/69596462-a7242700-0fd0-11ea-80e5-7b19b736da7a.png)

Just wonder if this is just my own problem due to library version or bug? If so, I would like to make a pull requrest?

**Comment by cmlarsen** [comment]
@aboveyunhai I've experienced the same thing.

**Comment by markusl** [comment]
Is this still a problem with the latest version?
