### ISSUE TITLE
CGContextSetLineDash: invalid dash array: at least one element must be non-zero.

### ISSUE THREAD

**Issue by schumannd** [bartgryszko/react-native-circular-progress#224]
I noticed that when setting/updating the progress, the following warning/error pops up in the xCode console:

    CGContextSetLineDash: invalid dash array: at least one element must be non-zero.

Any Idea what might be the problem here?

Here is my code:

      <AnimatedCircularProgress
        size={wp(13.1)} // weird situation where wp(13) causes circle to be cutoff.
        width={wp(2)}
        fill={progress * 100}
        tintColor={finalColor}
        backgroundColor={progressBackgroundColor}
        rotation={0}
        lineCap="round">
        {() => (
          <View style={[styles.circle, { backgroundColor: finalColor }]}>
            <Image source={playImgInv} style={styles.playImg} />
          </View>
        )}
      </AnimatedCircularProgress>

progress is updated periodically, and every time it is, the error occurs.
wp(13) = 13 percent of device width

**Comment by lukebars** [comment]
Noticed the strangest thing. This warning stops popping when `backgroundColor` prop isn't provided

**Comment by lukebars** [comment]
Looks like `dashedBackground` is the cause here. The default is [0,0] so that explains `at least one element must be non-zero`

**Comment by markusl** [comment]
Is this still a problem with the latest version?
