### ISSUE TITLE
1.3.5 Version not filling

### ISSUE THREAD

**Issue by Dellybro** [bartgryszko/react-native-circular-progress#229]
When i give the component a fill, it does not render the fill nor does it render new fills.

This seemed to work in 1.3.4, all of a sudden my program has stopped working the way it was supposed to

**Comment by JacopoKenzo** [comment]
Same problem here! 😓

**Comment by Dellybro** [comment]
For now i think everyone who is having this issue, should just install version 1.3.4 that is what i've done and the component should go back to working.

**Comment by aboveyunhai** [comment]
Please read the #227 regarding the issue merge.
Duplicate of #228 ,  check the fix.
