### ISSUE TITLE
tintColor and fill are not working in 1.3.4 or 1.3.5 version

### ISSUE THREAD

**Issue by sandeepg1220** [bartgryszko/react-native-circular-progress#231]
tintColor and fill are not working in 1.3.4 or 1.3.5 version. Previously worked perfectly.
If we give preFill prop it will display colour on loading.If the state is changed not working.

**Comment by markusl** [comment]
Hi @sandeepg1220! Thanks for reporting the issue. Since this is a community maintained package, would it be possible for you to check what might be the problem and possibly check in a pull request to improve the situation?

Best regards,
Markus

**Comment by markusl** [comment]
@sandeepg1220 do you still see the problem with the latest version?

Br, Markus
