### ISSUE TITLE
Warning in CircularProgress

### ISSUE THREAD

**Issue by SPineapple** [bartgryszko/react-native-circular-progress#232]
I am having this issue when my app re-renders (this happens when a button is pressed), even though I followed the example usage guideline I keep having it: 

`Warning: Failed prop type: The prop `fill` is marked as required in CircularProgress, but its value is undefined` 

fill prop is there, and it has a value by giving it in  
```
<AnimatedCircularProgress
fill={fill}
 > {(fill)=><Text>some value</Text>}
</AnimatedCircularProgress>
```

I don't know where or what should I do?

I am using Expo-cli version sdk 36.

**Comment by markusl** [comment]
I believe this is now fixed by #234.
