### ISSUE TITLE
App UI freeze on device

### ISSUE THREAD

**Issue by mandelmonkey** [bartgryszko/react-native-circular-progress#242]
This component seemed to cause my app UI to freeze on the device (android) after a while

```
 <AnimatedCircularProgress
                    size={progressSize}
                    width={15}
                    fill={syncProgress}
                    tintColor="#454648"
                    onAnimationComplete={() => CustomLog('onAnimationComplete')}
                      backgroundColor="#9ea6a9" />

```

if I removed this component the freeze no longer happened

i'm new to react so wondered if there was any mistake I am making?

**Comment by zeritte** [comment]
you also need to install react-native-svg package. make sure you have it properly

**Comment by mandelmonkey** [comment]
I discovered that the freezing was not caused by this repo
