### ISSUE TITLE
dashedTint not working

### ISSUE THREAD

**Issue by hoanglm4** [bartgryszko/react-native-circular-progress#243]
I using dashedBackground working fine. But dashedTint not working.
```
<AnimatedCircularProgress
                    size={129}
                    width={13}
                    fill={1}
                    tintColor={'#4790C0'}
                    backgroundColor={"rgba(77, 160, 215, 0.2)"}
                    ref={this._circularProgressRef}
                    rotation={-90}
                    arcSweepAngle={180}
                    style={iconRemainTime}
                    fillTransparency={false}
                    dashedBackground={{width: 2, gap: 5}}
                    dashedTint={{width: 2, gap: 5}}
                />
```
[Captured screen](https://drive.google.com/file/d/11PbQCkdiFq_5PI-QUYuEAXEYr_oconhX/view?usp=sharing)

iOS simulator iPhone 11 Pro (13.4.1)
react-native-circular-progress: 1.3.6

**Comment by aboveyunhai** [comment]
The current version from npm install package does not include `dashtint`. For newest version, you might want to directly install from github page

**Comment by hoanglm4** [comment]
ok. dashtint is included when i install from github page
