### ISSUE TITLE
ViewPropTypes has been deprecated in React Native

### ISSUE THREAD

**Issue by vitalyiegorov** [bartgryszko/react-native-circular-progress#244]
Using React Native 0.62.2
PropTypes has been deprecated and will be removed https://github.com/react-native-community/discussions-and-proposals/issues/29

We are using this package with [React native web](https://github.com/necolas/react-native-web) and after 0.12 release it throws an error:
`node_modules/react-native-circular-progress/src/CircularProgress.js
Attempted import error: 'ViewPropTypes' is not exported from 'react-native-web/dist/index'.`

As they have already removed the `PropTypes` from their exports.

a possible npm script fix:
`"fix:react-native-circular-progress": "sed -e \"s/ViewPropTypes.style,/PropTypes.object,/g\" -i.bak ./node_modules/react-native-circular-progress/src/CircularProgress.js",`

**Comment by aboveyunhai** [comment]
since `ViewPropTypes` is only for runtime checking, simply removing it from `CircularProgress.js` is my best bet if you don't want to execute the script every time.

**Comment by markusl** [comment]
@vitalyiegorov you can also provide a pull request to get this quickly fixed :)

**Comment by markusl** [comment]
I believe this is now resolved.

**Comment by lavor** [comment]
@markusl Could you release the new version with this fix, please?

**Comment by Stoneski93** [comment]
@lavor To work it on react-native-web you need also https://github.com/bakerface/react-native-svg-web
@markusl When that fix will be release?

**Comment by hotchpotch** [comment]
#247 it works well on my project.
Could you please the new version 🙏
