### ISSUE TITLE
Duration run incorrectly

### ISSUE THREAD

**Issue by tuan8797** [bartgryszko/react-native-circular-progress#252]
When i set duration is 60000 (1 minutes). The animation run too fast when start and too slow when it reach end

**Comment by aboveyunhai** [comment]
the default animation behavior is `Easing.ease`, 
You can change it by `import { Easing } from 'react-native';` and add prop `easing={()=>Easing.out(Easing.linear)}` or whatever behavior you prefer

**Comment by tuan8797** [comment]
@aboveyunhai thank you very much!!
