### ISSUE TITLE
how to re initiate the progress when the animation is complete.. please help

### ISSUE THREAD

**Issue by victorsamson1168** [bartgryszko/react-native-circular-progress#307]

**Comment by lytieunuong1** [comment]
You can use ref to save the progress then call `reAnimate` function on `onAnimatioComplete`. Here is an example
`
const reAnimation = async ({finished}) => {
    // Have to check finished, if not it will be loop because calling the reAnimate function
    if (timerRef.current && finished) {
      timerRef.current?.reAnimate(
        0,
        100,
        1000,
      );
    }
  };

return <AnimatedCircularProgress
                  ref={ref => {
                    if (timerRef) {
                      timerRef.current = ref;
                    }
                  }}
                  duration={1000}
                  size={28}
                  width={14}
                  fill={100}
                  rotation={0}
                  onAnimationComplete={reAnimation}
                />`

**Comment by markusl** [comment]
Since there are no follow-up questions, I assume @lytieunuong1's answer solved the question
