### ISSUE TITLE
Is there a way to add to shadow at the end of circular progress component?

### ISSUE THREAD

**Issue by Mactub07** [bartgryszko/react-native-circular-progress#62]

**Comment by Mactub07** [comment]
@
![image](https://cloud.githubusercontent.com/assets/13048119/26755560/4422fd7c-4898-11e7-9694-cbc28be08344.jpeg)

**Comment by Mactub07** [comment]
Like in green circle. If fill>100% I need to show shadow and gradient

**Comment by sytolk** [comment]
Maybe this issue:
https://github.com/bgryszko/react-native-circular-progress/issues/41
and implementation will help you:
https://github.com/fdnhkj/react-native-conical-gradient

**Comment by markusl** [comment]
Closing this issue as inactive. Please open a new one if there is a new issue with the library.

BR,
Markus
