### ISSUE TITLE
Feature request: colors for different parts of the circle

### ISSUE THREAD

**Issue by jhalborg** [bartgryszko/react-native-circular-progress#84]
Hey, 

First of all, thanks for a cool lib! Great work!

I have a client requirement for a cicle like this:
![image](https://user-images.githubusercontent.com/6643672/30641071-fcef0c20-9e05-11e7-91e5-25505922fe11.png)
preferably with an animation that plays when the component shows. 

I haven't had the oppotunity to look into the source for this lib yet, but I was thinking if you (or someone reading this) could help me out with either directions for- or implementation of this?

**Comment by robertobrogi** [comment]
have you find the solution for this?

**Comment by jhalborg** [comment]
Nope, not yet

**Comment by koolkarni** [comment]
can we do this ?

**Comment by Jacse** [comment]
Moving discussion to #163
