### ISSUE TITLE
Become a maintainer of this package

### ISSUE THREAD

**Issue by bartgryszko** [bartgryszko/react-native-circular-progress#98]
I'd be happy accept help maintaining this package & give write rights to people that would like to help fixing recent bugs / updating package to the newest react / native version, reviewing and merging PRs etc.

**Comment by Jacse** [comment]
It looks like you've already found some helping hands but if not I would be glad to help out.

**Comment by bgryszko** [comment]
Hi @Jacse, I did, big thanks to @markusl! I believe we'll still appreciate help. Let's just `assign yourself` any issue / PR that you'd be handling to avoid doubling the work.

Thanks!

**Comment by Jacse** [comment]
I think I'll close this since @markusl and I seem to be doing ok with maintaining the repo at the moment.
